### ISSUE TITLE
I can't import library.

### ISSUE THREAD

**Issue by malcolm83** [LMU-Seminar-LLMs/TopicGPT#3]
When the error occurs as shown below, it does not work. Please check.

from topicgpt.TopicGPT import TopicGPT
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\topicgpt\TopicGPT.py", line 6, in <module>
    from topicgpt.Clustering import Clustering_and_DimRed
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\topicgpt\Clustering.py", line 11, in <module>
    class Clustering_and_DimRed():
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\topicgpt\Clustering.py", line 77, in Clustering_and_DimRed
    def reduce_dimensions_umap(self, embeddings: np.ndarray) -> Tuple[np.ndarray, umap.UMAP]:
NameError: name 'Tuple' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-60-d6cb19597990>", line 1, in <module>
    from topicgpt.TopicGPT import TopicGPT
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\topicgpt\TopicGPT.py", line 14, in <module>
    from Clustering import Clustering_and_DimRed
  File "C:\Program Files\JetBrains\PyCharm 2022.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'Clustering'

**Comment by ArikReuter** [comment]
Hi, thanks a lot for pointing this out. This is actually a known issue and will be fixed very soon. In the meantime can maybe try the 0.0.2 version of TopicGPT which shouldn't have this issue.

**Comment by malcolm83** [comment]
thank you so much

2023년 9월 7일 (목) 오후 5:26, ArikReuter ***@***.***>님이 작성:

**Comment by malcolm83** [comment]
iI gave the first star. I hope it turns out as well as you think. I set it
to 0.0.2 and it runs fine. If you want feedback or anything like that, I'll
work hard. Cheer up and make it

2023년 9월 7일 (목) 오후 5:28, Wonkuk Park ***@***.***>님이 작성:

**Comment by ol4716** [comment]
Hi-- I believe this issue is ongoing, and I still get the same error message when using version 0.0.2. Is there another workaround for this issue?
